services:
    flask:
        build:
            context: .
            dockerfile: Dockerfile
        image: htmx-quart
        volumes:
            - $PWD:/opt/app
        restart: always
        ports:
          - 5000:5000
        working_dir: /opt/app
        command: python app.py 5000 --debug
        healthcheck:
            test: curl -f http://localhost:5000/ping || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s